Authentification:
    path:      /
    defaults: { _controller: MPGsbBundle:Accueil:index}
Accueil:
    path:      /accueil
    defaults: { _controller: MPGsbBundle:Accueil:index}

Afficher:
    path:       /Medicament
    defaults: {_controller: MPGsbBundle:Medicament:liste}

Form:
    path:      /Form
    defaults: {_controller: MPGsbBundle:Medicament:Form}
