Authentification:
    path:      /
    defaults: { _controller: MPGsbBundle:Accueil:index}
Accueil:
    path:      /accueil
    defaults: { _controller: MPGsbBundle:Accueil:index}

Afficher:
    path:       /Medicament
    defaults: {_controller: MPGsbBundle:Medicament:liste}

Form:
    path:      /Form/{action}/{id}
    defaults: {_controller: MPGsbBundle:Medicament:Form}

Supprimer:

    path:      /Supprimer/{id}

    defaults:  { _controller: MPGsbBundle:Medicament:Supprimer}
